version: "1"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "bookingMachine"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "127.0.0.1:5433:5432"